import { beforeEach, describe, expect, it, vi } from "vitest";

const { catalogServiceMock, withAuthMock } = vi.hoisted(() => ({
  catalogServiceMock: { create: vi.fn(), update: vi.fn() },
  withAuthMock: vi.fn(),
}));

vi.mock("./service", () => ({ catalogService: catalogServiceMock }));
vi.mock("@/shared/auth/auth-guard", () => ({ withAuth: withAuthMock }));
vi.mock("next/headers", () => ({ headers: vi.fn().mockResolvedValue(new Headers()) }));

import { createCatalogItem, updateCatalogItem } from "./actions";

const FAKE_SESSION = { user: { id: "u1", role: "ADMIN" } };

beforeEach(() => {
  vi.clearAllMocks();
  withAuthMock.mockImplementation((_roles, fn) => fn(FAKE_SESSION));
  catalogServiceMock.create.mockResolvedValue({ id: 1, name: "X" });
  catalogServiceMock.update.mockResolvedValue({ id: 1, name: "X" });
});

// ─── createCatalogItem ────────────────────────────────────────────────────────

describe("createCatalogItem — schema routing", () => {
  it("rejects empty name for any basic type", async () => {
    const res = await createCatalogItem("company", { name: "" });
    expect(res.success).toBe(false);
    expect(catalogServiceMock.create).not.toHaveBeenCalled();
  });

  it("accepts valid name for basic catalog types", async () => {
    const types = ["company", "workplace", "workArea", "jobPosition",
      "occupationalExposure", "workDisability", "referralLevel",
      "allergyCategory", "diseaseType", "bloodType", "habitCatalog",
      "suspensionHour", "relationshipType"] as const;

    for (const type of types) {
      vi.clearAllMocks();
      withAuthMock.mockImplementation((_roles, fn) => fn(FAKE_SESSION));
      catalogServiceMock.create.mockResolvedValue({ id: 1, name: "X" });

      const res = await createCatalogItem(type, { name: "Valid Name" });
      expect(res.success, `type: ${type}`).toBe(true);
      expect(catalogServiceMock.create, `type: ${type}`).toHaveBeenCalled();
    }
  });

  // allergenCatalog requires allergyCategoryId
  it("allergenCatalog: rejects missing allergyCategoryId", async () => {
    const res = await createCatalogItem("allergenCatalog", { name: "Polen" });
    expect(res.success).toBe(false);
    expect(catalogServiceMock.create).not.toHaveBeenCalled();
  });

  it("allergenCatalog: accepts name + allergyCategoryId", async () => {
    const res = await createCatalogItem("allergenCatalog", { name: "Polen", allergyCategoryId: 2 });
    expect(res.success).toBe(true);
    expect(catalogServiceMock.create).toHaveBeenCalledWith(
      "allergenCatalog",
      { name: "Polen", allergyCategoryId: 2 },
      FAKE_SESSION.user.id
    );
  });

  // exerciseCatalog: code is auto-generated, only name required from the UI
  it("exerciseCatalog: rejects missing name", async () => {
    const res = await createCatalogItem("exerciseCatalog", {});
    expect(res.success).toBe(false);
    expect(catalogServiceMock.create).not.toHaveBeenCalled();
  });

  it("exerciseCatalog: accepts name only (code auto-generated by repo)", async () => {
    const res = await createCatalogItem("exerciseCatalog", { name: "GYM" });
    expect(res.success).toBe(true);
    expect(catalogServiceMock.create).toHaveBeenCalledWith(
      "exerciseCatalog",
      { name: "GYM" },
      FAKE_SESSION.user.id
    );
  });

  // maritalStatus: sex is optional but must be preserved when provided
  it("maritalStatus: accepts name without sex", async () => {
    const res = await createCatalogItem("maritalStatus", { name: "Soltero" });
    expect(res.success).toBe(true);
  });

  it("maritalStatus: passes sex to service when provided", async () => {
    const res = await createCatalogItem("maritalStatus", { name: "Casada", sex: "FEMALE" });
    expect(res.success).toBe(true);
    expect(catalogServiceMock.create).toHaveBeenCalledWith(
      "maritalStatus",
      { name: "Casada", sex: "FEMALE" },
      FAKE_SESSION.user.id
    );
  });

  it("maritalStatus: strips sex when createCatalogSchema was used (regression guard)", async () => {
    // This test would fail if maritalStatus accidentally used createCatalogSchema instead
    // of maritalStatusSchema, which strips unknown keys and silently drops sex.
    const res = await createCatalogItem("maritalStatus", { name: "Casada", sex: "FEMALE" });
    expect(res.success).toBe(true);
    const callArg = catalogServiceMock.create.mock.calls[0][1];
    expect(callArg).toHaveProperty("sex", "FEMALE");
  });
});

// ─── updateCatalogItem ────────────────────────────────────────────────────────

describe("updateCatalogItem", () => {
  it("rejects empty name", async () => {
    const res = await updateCatalogItem("company", 1, { name: "" });
    expect(res.success).toBe(false);
    expect(catalogServiceMock.update).not.toHaveBeenCalled();
  });

  it("accepts partial payload with active only", async () => {
    const res = await updateCatalogItem("company", 1, { active: false });
    expect(res.success).toBe(true);
  });

  it("calls service with id and validated data", async () => {
    const res = await updateCatalogItem("company", 5, { name: "Acme" });
    expect(res.success).toBe(true);
    expect(catalogServiceMock.update).toHaveBeenCalledWith("company", 5, { name: "Acme" }, FAKE_SESSION.user.id);
  });
});
